[package]
name = "rongu"
version = "0.1.0"
edition = "2018"

[dependencies]
warp = "0.3"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.15", features = ["full"] }
log = "0.4.14"
env_logger = "0.8.4"